version: '3'

services:
    backend:
        build: ./backend
        expose: 
            - 3500
        ports:
            - 3500:3500
        #volumes: ./backend:/app

    frontend:
        build: ./frontend
        expose:
            - 3000
        ports:
            - 3000:3000

        depends_on: 
            - backend